local Concord = require("lib.concord")

Concord.component("drawable")
Concord.component("decorativePlane")
Concord.component("obstaclePlane")
Concord.component("playerControlled")
Concord.component("levelFinishAIControlled")
Concord.component("camera")
Concord.component("character")
Concord.component("alive")
Concord.component("destroyOutOfBounds")
Concord.component("respawn")
Concord.component("gravityNotColliding")
Concord.component("canCollideWithObstacles")
Concord.component("canCollideWithBoundaries")
Concord.component("limb")
Concord.component("detachedLimb")
Concord.component("limbDeatchRequest")

Concord.component("bloodParticle")