local Concord = require("lib.concord")

Concord.component("drawable")
Concord.component("decorativePlane")
Concord.component("obstaclePlane")
Concord.component("playerControlled")
Concord.component("camera")
Concord.component("character")
Concord.component("alive")
Concord.component("destroyAboveCamera")
Concord.component("respawn")
Concord.component("gravityNotColliding")
Concord.component("collidesWithObstacles")
Concord.component("limb")
Concord.component("lastObstacle")