return {
    main_menu_btn_play_story = "PLAY STORY",
    main_menu_btn_play_daily_challenge = "PLAY DAILY CHALLENGE",
    main_menu_btn_play_endless_mode = "PLAY ENDLESS MODE",
    btn_settings = "OPTIONS",
    btn_exit_game = "EXIT TO DESKTOP",
    btn_back = "BACK",
    btn_level_selection_start_game = "PLAY SELECTED LEVEL",

    lbl_hud_progress = "PROGRESS",
    lbl_hud_score = "SCORE",
    lbl_hud_speed = "SPEED",
    lbl_hud_speed_units = "kph",

    lbl_game_you_died = "YOU DIED",
    lbl_game_stats_progress = "Progress: %s%%",
    lbl_game_stats_score = "Score: %d",
    lbl_game_stats_time = "Time: %s",
    btn_game_restart_level = "RESTART (R)",
    btn_game_exit_to_menu = "EXIT TO MENU",
    lbl_game_paused = "PAUSED",
    lbl_game_paused_continue = "Press ESC to continue",
    btn_game_paused_continue = "CONTINUE",
    lbl_game_level_complete = "LEVEL COMPLETE",
    btn_game_next_level = "NEXT LEVEL",
}