return {
    main_menu_btn_play_story = "PLAY STORY",
    main_menu_btn_play_daily_challenge = "PLAY DAILY CHALLENGE",
    main_menu_btn_play_endless_mode = "PLAY ENDLESS MODE",
    btn_settings = "OPTIONS",
    btn_exit_game = "EXIT TO DESKTOP",
    btn_back = "BACK",
    btn_level_selection_start_game = "START GAME",
    btn_level_selection_level_locked = "LOCKED",
    lbl_level_stats_highscore = "Highscore",
    lbl_level_stats_best_time = "Best time",
    lbl_level_stats_deaths = "Deaths",
    lbl_level_stats_limbs_lost = "Limbs lost",
    lbl_level_stats_rating_requirements = "Requirements",
    lbl_level_stats_rating_requirements_score = "Score: %d",
    lbl_level_stats_rating_requirements_complete = "Complete level",

    lbl_hud_progress = "PROGRESS",
    lbl_hud_score = "SCORE",
    lbl_hud_speed = "SPEED",
    lbl_hud_speed_units = "kph",

    lbl_game_you_died = "YOU DIED",
    lbl_game_stats_progress = "Progress: %s%%",
    lbl_game_stats_score = "Score: %d",
    lbl_game_stats_time = "Time: %s",
    btn_game_restart_level = "RESTART (R)",
    btn_game_exit_to_menu = "EXIT TO MENU",
    lbl_game_paused = "PAUSED",
    lbl_game_paused_continue = "Press ESC to continue",
    btn_game_paused_continue = "CONTINUE",
    lbl_game_level_complete = "LEVEL COMPLETE",
    btn_game_next_level = "NEXT LEVEL (F)",

    lbl_settings_music_volume = "Music volume",
    lbl_settings_master_volume = "Master volume",
    lbl_settings_plane_fading = "Obstacle fading",
    lbl_settings_speed_lines = "Speed lines",
    lbl_settings_world_quality = "World quality",
    lbl_settings_particles_quality = "Particles quality",
    lbl_settings_motion_blur = "Motion blur",
    lbl_settings_decals = "Decals",
    btn_settings_close = "Save and close",
    lbl_settings_disabled = "Disabled",
    lbl_settings_enabled = "Enabled",
    lbl_settings_low = "Low",
    lbl_settings_medium = "Medium",
    lbl_settings_high = "High",
    lbl_settings_language = "Language",
    lbl_settings_lang_english = "English",
    lbl_settings_lang_russian = "Russian",
    lbl_settings_window_mode = "Window mode",
    lbl_settings_windowed = "Windowed",
    lbl_settings_borderless = "Borderless",
    lbl_settings_fullscreen = "Fullscreen",
    lbl_settings_vsync = "VSync",

    lbl_game_finish_new_highscore = "New highscore!",
    lbl_game_finish_new_best_time = "New best time!",

    lbl_splash_press_any_button = "PRESS ANY BUTTON",
    lbl_splash_loading = "Connecting to Steam...",

    lbl_intro_press_to_jump = "PRESS %s TO JUMP",
}