return {
    main_menu_btn_play_story = "КАМПАНИЯ",
    main_menu_btn_play_daily_challenge = "ЕЖЕДНЕВНОЕ ИСПЫТАНИЕ",
    main_menu_btn_play_endless_mode = "БЕСКОНЕЧНЫЙ РЕЖИМ",
    btn_settings = "НАСТРОЙКИ",
    btn_exit_game = "ВЫЙТИ ИЗ ИГРЫ",
    btn_back = "НАЗАД",
    btn_level_selection_start_game = "НАЧАТЬ ИГРУ",
    btn_level_selection_level_locked = "ЗАБЛОКИРОВАНО",
    lbl_level_stats_highscore = "Лучший счёт",
    lbl_level_stats_best_time = "Лучшее время",
    lbl_level_stats_deaths = "Смертей",
    lbl_level_stats_limbs_lost = "Потеряно конечностей",

    lbl_hud_progress = "ПРОГРЕСС",
    lbl_hud_score = "ОЧКИ",
    lbl_hud_speed = "СКОРОСТЬ",
    lbl_hud_speed_units = "КМ/Ч",

    lbl_game_you_died = "ВЫ РАЗБИЛИСЬ",
    lbl_game_stats_progress = "Прогресс: %s%%",
    lbl_game_stats_score = "Очки: %d",
    lbl_game_stats_time = "Время: %s",
    btn_game_restart_level = "НАЧАТЬ ЗАНОВО (R)",
    btn_game_exit_to_menu = "ВЫЙТИ В МЕНЮ",
    lbl_game_paused = "ПАУЗА",
    lbl_game_paused_continue = "Нажмите ESC, чтобы продолжить",
    btn_game_paused_continue = "ПРОДОЛЖИТЬ",
    lbl_game_level_complete = "УРОВЕНЬ ПРОЙДЕН",
    btn_game_next_level = "СЛЕДУЮЩИЙ УРОВЕНЬ (F)",

    lbl_settings_music_volume = "Громкость музыки",
    lbl_settings_master_volume = "Общая громкость",
    lbl_settings_plane_fading = "Прозрачность препятствий",
    lbl_settings_speed_lines = "Эффект скорости",
    lbl_settings_world_quality = "Качество мира",
    lbl_settings_particles_quality = "Качество частиц",
    lbl_settings_motion_blur = "Размытие в движении",
    lbl_settings_decals = "Декали",
    btn_settings_close = "Сохранить и закрыть",
    lbl_settings_disabled = "Выкл.",
    lbl_settings_enabled = "Вкл.",
    lbl_settings_low = "Низк.",
    lbl_settings_medium = "Средн.",
    lbl_settings_high = "Высок.",
    lbl_settings_language = "Язык интерфейса",
    lbl_settings_lang_english = "English",
    lbl_settings_lang_russian = "Русский",
    lbl_settings_window_mode = "Режим экрана",
    lbl_settings_windowed = "В окне",
    lbl_settings_borderless = "Без рамки",
    lbl_settings_fullscreen = "Полный экран",
    lbl_settings_vsync = "Верт. синхронизация",

    lbl_game_finish_new_highscore = "Новый рекорд!",
    lbl_game_finish_new_best_time = "Новый рекорд!"
}