return {
    main_menu_btn_play_story = "КАМПАНИЯ",
    main_menu_btn_play_daily_challenge = "ЕЖЕДНЕВНОЕ ИСПЫТАНИЕ",
    main_menu_btn_play_endless_mode = "БЕСКОНЕЧНЫЙ РЕЖИМ",
    btn_settings = "НАСТРОЙКИ ИГРЫ",
    btn_exit_game = "ВЫЙТИ ИЗ ИГРЫ",
    btn_back = "НАЗАД",
    btn_level_selection_start_game = "ИГРАТЬ",

    lbl_hud_progress = "ПРОГРЕСС",
    lbl_hud_score = "ОЧКИ",
    lbl_hud_speed = "СКОРОСТЬ",
    lbl_hud_speed_units = "КМ/Ч",

    lbl_game_you_died = "ВЫ РАЗБИЛИСЬ",
    lbl_game_stats_progress = "Прогресс: %s%%",
    lbl_game_stats_score = "Очки: %d",
    lbl_game_stats_time = "Время: %d",
    btn_game_restart_level = "НАЧАТЬ ЗАНОВО (R)",
    btn_game_exit_to_menu = "ВЫЙТИ В МЕНЮ",
    lbl_game_paused = "ПАУЗА",
    lbl_game_paused_continue = "Нажмите ESC, чтобы продолжить",
    btn_game_paused_continue = "ПРОДОЛЖИТЬ",
    lbl_game_level_complete = "УРОВЕНЬ ПРОЙДЕН",
    btn_game_next_level = "СЛЕДУЮЩИЙ УРОВЕНЬ",
}