local Concord = require("lib.concord")

Concord.component("drawable")
Concord.component("obstaclePlane")
Concord.component("controlledByPlayer")
Concord.component("controlledByAI")
Concord.component("character")
Concord.component("alive")
Concord.component("destroyOutOfBounds")
Concord.component("gravityNotColliding")
Concord.component("canCollideWithObstacles")
Concord.component("canCollideWithBoundaries")
Concord.component("limb")
Concord.component("detachedLimb")
Concord.component("limbDeatchRequest")
Concord.component("breakableObstacle")
Concord.component("tunnelCenter")
Concord.component("tunnelTop")

Concord.component("bloodParticle")