return {
    name = "Flesh Hell 1",
    nextLevel = "meat2",

    fallSpeed = 47,
    fogColor = {25, 10, 0},
    fogDistance = 70,
    playerRotationMode = "sinusoid",
    playerRotationSpeed = 0.2,
    playerRotationChangeSpeed = 0.01,

    sidePlanesCount = 60,
    sidePlanesRandomBrightness = true,
    sidePlanesBrightness = 0.95,
    sidePlanes = {
        {
            textures = {
                "levels/meat/side_planes/cave1",
                "levels/meat/side_planes/cave2",
            },
        },
        {
            textures = {
                "levels/meat/side_planes/flesh",
            },
        },
    },

    planeTypes = {
        wall_hands = {
            planes = {{ texture = "levels/meat/obstacles/wall_hands", }},
        },
        stone_hole = {
            planes = {{ texture = "levels/meat/obstacles/stone_obstacle1", }},
        },
        stone_small_hole = {
            planes = {{ texture = "levels/meat/obstacles/stone_obstacle2", }},
        },
        stone_small_hole2 = {
            planes = {{ texture = "levels/meat/obstacles/stone_obstacle4", }},
        },
        stone_side_long_hole = {
            planes = {{ texture = "levels/meat/obstacles/stone_obstacle3", }},
        },
        stone_breakable_wall = {
            planes = {{ texture = "levels/meat/obstacles/stone_obstacle_breakable", breakable = true }},
        },
        old_door = {
            planes = {
                { texture = "levels/vents/middle_door_frame" },
                { texture = "levels/vents/middle_door", position = {0, 0, -0.5}, velocity = {-8, 0, 0}, moveDelay = 1, },
            },
        },
        meat_long_middle_thing = {
            planes = {
                { texture = "levels/meat/obstacles/long_meat_middle_thing" },
            },
        },
        meat_half_wall = {
            planes = {
                { texture = "levels/meat/obstacles/meat_obstacle_half" },
            },
        },
    },

    planes = {
        { distance = 100, name = "stone_hole", rotation = 0 },
        { distance = 20, name = "stone_small_hole", rotation = 0 },
        { distance = 27, name = "stone_side_long_hole", rotation = 180 },
        { distance = 25, name = "stone_small_hole", rotation = 180 },
        { distance = 22, name = "stone_small_hole2", rotation = 180 },
        { distance = 22, name = "stone_hole", rotation = 270 },
        { distance = 12, name = "stone_breakable_wall", rotation = 0 },
        { distance = 30, name = "wall_hands", rotation = 90, tunnelShape = { rotationSpeed = 0.2 } },
        { distance = 5, name = "wall_hands", rotation = 180 },
        { distance = 6, name = "wall_hands", rotation = 90 },
        { distance = 3, name = "wall_hands", rotation = 0 },
        { distance = 8, name = "wall_hands", rotation = 270 },
        { distance = 4, name = "wall_hands", rotation = 180 },
        { distance = 2, name = "wall_hands", rotation = 90 },
        { distance = 10, name = "wall_hands", rotation = 0 },
        { distance = 2, name = "wall_hands", rotation = 90 },
        { distance = 5, name = "wall_hands", rotation = 180 },
        { distance = 6, name = "wall_hands", rotation = 90 },
        { distance = 3, name = "wall_hands", rotation = 0 },
        { distance = 8, name = "wall_hands", rotation = 270 },
        { distance = 4, name = "wall_hands", rotation = 180 },
        { distance = 2, name = "wall_hands", rotation = 90 },
        { distance = 10, name = "wall_hands", rotation = 0 },
        { distance = 6, name = "wall_hands", rotation = 90 },
        { distance = 5, name = "wall_hands", rotation = 180 },
        { distance = 6, name = "wall_hands", rotation = 90 },
        { distance = 3, name = "wall_hands", rotation = 0 },
        { distance = 8, name = "wall_hands", rotation = 270 },
        { distance = 8, name = "old_door", rotation = 0 },
        { distance = 10, name = "stone_breakable_wall", rotation = 0, switchSidePlanes = true, },
        { distance = 30, tunnelShape = { direction = {10, 0}, rotationSpeed = 0.2 },},
        { distance = 30, name = "meat_long_middle_thing" },
        { distance = 15, name = "meat_half_wall", rotation = 90, },
        { distance = 15, tunnelShape = { direction = {0, 0}, rotationSpeed = 0 },},
        { distance = 20, tunnelShape = { direction = {10, 0}, rotationSpeed = 0.8 },},
        { distance = 30, name = "meat_long_middle_thing" },
        { distance = 30, name = "meat_half_wall", rotation = 180 },
        { distance = 20, name = "meat_long_middle_thing", rotation = 180 },
        { distance = 15, name = "meat_long_middle_thing", rotation = 90 },
        { distance = 17, name = "meat_half_wall" },
        { distance = 14, name = "meat_long_middle_thing", rotation = 180 },
        { distance = 19, name = "meat_long_middle_thing", rotation = 90 },
        { distance = 20, name = "meat_half_wall", rotation = 90 },
        { distance = 15, name = "meat_long_middle_thing" },
        { distance = 17, name = "meat_half_wall", rotation = 180 },
        { distance = 20, name = "meat_long_middle_thing" },
        { distance = 30, name = "meat_long_middle_thing" },
        { distance = 19, name = "meat_long_middle_thing", rotation = 270 },
        { distance = 5, name = "meat_long_middle_thing", rotation = 90 },
        { distance = 17, name = "meat_half_wall", rotation = 0 },

        { distance = 15, tunnelShape = { direction = {0, 0}, rotationSpeed = 2 },},
        { distance = 40, name = "meat_half_wall" },
        { distance = 10, name = "meat_long_middle_thing" },
        { distance = 10, name = "meat_half_wall" },
        { distance = 10, name = "meat_long_middle_thing" },
        { distance = 10, name = "meat_half_wall" },
        { distance = 10, name = "meat_long_middle_thing" },
        { distance = 10, name = "meat_half_wall" },
        { distance = 10, name = "meat_long_middle_thing" },
        { distance = 10, name = "meat_half_wall" },

        { distance = 10, name = "meat_long_middle_thing", rotation = 90 },
        { distance = 15, tunnelShape = { direction = {0, 8}, rotationSpeed = 3 },},

        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 5, name = "meat_long_middle_thing" },
        { distance = 5, name = "meat_half_wall" },
        { distance = 10, name = "meat_long_middle_thing", rotation = 90 },
        { distance = 15, tunnelShape = { direction = {0, 0}, rotationSpeed = 0.25 },},
    },
}