name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Build the applications
      - uses: nhartland/love-build@v1-beta2
        id: love-build
        with:
         app_name: 'No Parachute'
         love_version: '11.3'
      # Upload the built applications
      - uses: actions/upload-artifact@v1
        with:
          name: hw_win32-build
          path: ${{ steps.love-build.outputs.win32-filename }}
